spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.84.177.146:3306/b_incent?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&nullCatalogMeansCurrent=true
    username: root
    password: "T4JK3b90PYd?hD4Fm?]%"
  data:
    redis:
      host: r-t4nimvqs3hsr60ldttpd.redis.singapore.rds.aliyuncs.com
      port: 6379
      password: "7MLZuP-x8J-dH_Z"
      database: 0
      repositories:
        enabled: false
  servlet:
    multipart:
      max-file-size: 5012MB
      max-request-size: 5012MB
  mail:
    host: smtp.163.com	  # QQ邮箱SMTP服务器
    port: 465
    username: 18189270679@163.com
    password: TQUtm33eiShjiJ4a  # 授权码，不是密码
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true  # 启用SSL
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
    default-encoding: UTF-8
logging:
  level:
    org.apache.kafka: OFF
    kafka: OFF
    com.siom.medivh.server.mapper: error